# Ejercicio 1

Escribe un pequeño programa que calcule el máximo entre 4 números que debe introducir el usuario sin utilizar la función max de Python

In [2]:
DEBUG=0 # variable utilizada para hacer un DEBUG
        # si Debug=1 se mostrarán los pasos que se siguen en la ejecución del programa
        # si Debug=0 (o cualquier otro valor) no se mostrarán los carteles

cant=4   # cantidad de números que se leen para calcular el máximo (afecta al número de peticiones)
lista=[] # almacena los números que se leen
    
for x in range (cant):
    lista.append(int(input(f'Valor {x+1}: '))) 

maximo=lista[0]

for x in range (1,cant):
    
    if (DEBUG == 1):
        print()    # inserta una línea en blanco
        print(f'Comparo {lista[x]} con {maximo}')
    
    if lista[x]>maximo:
        maximo=lista[x]
        if (DEBUG == 1):
            print('Es mayor')
    else:
        if (DEBUG == 1):
            print('Es menor')
            

print()     # inserta una línea en blanco
print('El maximo es ', maximo)  # muestra el valor guardado en la variable 'm'

lista.clear()   # vacía la lista para evitar errores en la siguiente ejecución
    

Valor 1: 3
Valor 2: 4
Valor 3: 5
Valor 4: 3

Comparo 4 con 3
Es mayor

Comparo 5 con 4
Es mayor

Comparo 3 con 5
Es menor

El maximo es  5


# Ejercicio 2

- Crea un array de `Numpy` de 10 filas y 9 columnas de manera que el elemento $(i,j)$ sea  $\frac{1}{i+j-1}$ para $1\le i\le 10$ y $1\le j\le 9$. Ten en cuenta que las filas y columnas se numeran a partir de 1 pero en Python la numeración empieza en 0. El primer elemento del array debe ser 1.

- Crea ahora un array $B$ de números aleatorios entre 0 y 3 de tamaño $5\times 5$. Calcula $B^{8}$.

In [99]:
import numpy as np   # incluyo la biblioteca de Numpy
import copy

def imprime(matriz , n_decimales=3 , separador = '    '):
    
    cad='{0:.'
    cad+=str(n_decimales)
    cad+=('f}')
    
    print('[', end='')
    
    for i in range (matriz.shape[0]-1):
        
        if(i==0):
            print('[', end='')
        else:
            print(' [', end='')
        
        for j in range (matriz.shape[1]-1):
            
            if(j==matriz.shape[1]-2):
                print(cad.format(matriz[i][j],n_decimales), end='') 
                
            else:
                print(cad.format(matriz[i][j],n_decimales), end=separador)
                
        if(i==matriz.shape[0]-2):
            print(']]')
                
        else:
            print(']')



matriz_a=np.array([[(1/((i+1)+(j+1)-1)) for i in range (0,10)]for j in range (0,11)])
matriz_b=np.random.rand(6,6)*3
matriz_c=copy.copy(matriz_b)

for x in range (8):
    matriz_c*=matriz_c
    
print('Apartado a: \n')
imprime(matriz_a , 5 , '     ')
print() #linea en blanco

print('Apartado b: \n')
imprime(matriz_b , 5 ,  '       ')
print()

print('Apartado c: \n')
print(matriz_c)




Apartado a: 

[[1.00000     0.50000     0.33333     0.25000     0.20000     0.16667     0.14286     0.12500     0.11111]
 [0.50000     0.33333     0.25000     0.20000     0.16667     0.14286     0.12500     0.11111     0.10000]
 [0.33333     0.25000     0.20000     0.16667     0.14286     0.12500     0.11111     0.10000     0.09091]
 [0.25000     0.20000     0.16667     0.14286     0.12500     0.11111     0.10000     0.09091     0.08333]
 [0.20000     0.16667     0.14286     0.12500     0.11111     0.10000     0.09091     0.08333     0.07692]
 [0.16667     0.14286     0.12500     0.11111     0.10000     0.09091     0.08333     0.07692     0.07143]
 [0.14286     0.12500     0.11111     0.10000     0.09091     0.08333     0.07692     0.07143     0.06667]
 [0.12500     0.11111     0.10000     0.09091     0.08333     0.07692     0.07143     0.06667     0.06250]
 [0.11111     0.10000     0.09091     0.08333     0.07692     0.07143     0.06667     0.06250     0.05882]
 [0.10000     0.09091  