$Nombre: $ Jesús Muñoz Velasco

# Ejercicio 1

Escribe un pequeño programa que calcule el máximo entre 4 números que debe introducir el usuario sin utilizar la función max de Python

In [2]:
DEBUG=0 # variable utilizada para hacer un DEBUG
        # si Debug=1 se mostrarán los pasos que se siguen en la ejecución del programa
        # si Debug=0 (o cualquier otro valor) no se mostrarán los carteles

cant=4   # cantidad de números que se leen para calcular el máximo (afecta al número de peticiones)
lista=[] # almacena los números que se leen
    
for x in range (cant):
    lista.append(int(input(f'Valor {x+1}: '))) 

maximo=lista[0]

for x in range (1,cant):
    
    if (DEBUG == 1):
        print()    # inserta una línea en blanco
        print(f'Comparo {lista[x]} con {maximo}')
    
    if lista[x]>maximo:
        maximo=lista[x]
        if (DEBUG == 1):
            print('Es mayor')
    else:
        if (DEBUG == 1):
            print('Es menor')
            

print()     # inserta una línea en blanco
print('El maximo es ', maximo)  # muestra el valor guardado en la variable 'm'

lista.clear()   # vacía la lista para evitar errores en la siguiente ejecución
    

Valor 1: 2
Valor 2: 20
Valor 3: 50
Valor 4: 3

El maximo es  50


# Ejercicio 2

Crea un array de `Numpy` de 20 filas y 10 columnas de manera que el elemento $(i,j)$ sea  $\frac{1}{i^2+j-1}$ para $1\le i\le 20$ y $1\le j\le10$. Ten en cuenta que las filas y columnas se numeran a partir de 1 pero en Python la numeración empieza en 0. El primer elemento del array debe ser 1.

In [1]:
import numpy as np   # incluyo la biblioteca de Numpy

def imprime(matriz , n_decimales=3 , separador = '    '): #función que imprime una matriz bidimensional
    
    cad='{0:.'
    cad+=str(n_decimales)
    cad+=('f}')
    
    print('[', end='')
    
    for i in range (matriz.shape[0]-1):
        
        if(i==0):
            print('[', end='')
        else:
            print(' [', end='')
        
        for j in range (matriz.shape[1]-1):
            
            if(j==matriz.shape[1]-2):
                print(cad.format(matriz[i][j],n_decimales), end='') 
                
            else:
                print(cad.format(matriz[i][j],n_decimales), end=separador)
                
        if(i==matriz.shape[0]-2):
            print(']]')
                
        else:
            print(']')



matrizA=np.array([[(1/((i+1)**2+(j+1)-1)) for j in range (0,11)]for i in range (0,21)])

    
imprime(matrizA , 5 , '     ')


[[1.00000     0.50000     0.33333     0.25000     0.20000     0.16667     0.14286     0.12500     0.11111     0.10000]
 [0.25000     0.20000     0.16667     0.14286     0.12500     0.11111     0.10000     0.09091     0.08333     0.07692]
 [0.11111     0.10000     0.09091     0.08333     0.07692     0.07143     0.06667     0.06250     0.05882     0.05556]
 [0.06250     0.05882     0.05556     0.05263     0.05000     0.04762     0.04545     0.04348     0.04167     0.04000]
 [0.04000     0.03846     0.03704     0.03571     0.03448     0.03333     0.03226     0.03125     0.03030     0.02941]
 [0.02778     0.02703     0.02632     0.02564     0.02500     0.02439     0.02381     0.02326     0.02273     0.02222]
 [0.02041     0.02000     0.01961     0.01923     0.01887     0.01852     0.01818     0.01786     0.01754     0.01724]
 [0.01562     0.01538     0.01515     0.01493     0.01471     0.01449     0.01429     0.01408     0.01389     0.01370]
 [0.01235     0.01220     0.01205     0.01190   

# Ejercicio 3

Crea un vector con los elementos de la cuarta fila del array A

In [2]:
import numpy as np

def imprime(matriz , n_decimales=3 , separador = '    '): #función que imprime una matriz unidimensional
    
    cad='{0:.'
    cad+=str(n_decimales)
    cad+=('f}')
    
    print('[', end='')
    
    for i in range (matriz.shape[0]-1):
        if(i!=0):
            print(separador, end='')
            
        print(cad.format(matriz[i],n_decimales), end='') 
            
    print(']')        
            

fila_4=matrizA[3,:]

imprime(fila_4 , 5 , '     ')

[0.06250     0.05882     0.05556     0.05263     0.05000     0.04762     0.04545     0.04348     0.04167     0.04000]


# Ejercicio 4

Crea ahora un array $B$ de números aleatorios entre 0 y 1 de tamaño $5\times 5$. Calcula ${(B+2I)}^{8}$.

In [53]:
import numpy as np

matrizB=np.random.rand(5,5)
print('Matriz generada:')
print(matrizB)

ide=np.eye(5) #matriz identidad

resultado=np.linalg.matrix_power((matrizB + (2*ide)),2)

print()
print('Matriz (B+2I)^10:')
print(resultado)

Matriz generada:
[[0.22078222 0.1742529  0.42271731 0.31284591 0.47378487]
 [0.34194441 0.75223254 0.87948846 0.8871764  0.37455624]
 [0.61161235 0.62843959 0.77744629 0.44216835 0.76045038]
 [0.64665151 0.11911773 0.45557439 0.78286195 0.91591692]
 [0.70565506 0.48611134 0.80359599 0.92463918 0.672963  ]]

Matriz (B+2I)^10:
[[5.78662859 1.39979224 2.78934732 2.34495496 2.99184637]
 [3.07640204 8.47482863 5.71300127 5.75279247 3.67543613]
 [4.09441417 4.00397799 9.33798783 3.91061174 5.07491394]
 [4.20130203 1.50354738 3.64727464 9.10063461 5.69451412]
 [4.7089277  3.37536397 5.52699088 6.05202203 9.11912349]]
