# Primeros pasos con los Notebooks de IPython

En esta primera práctica vamos a ver algunas cuestiones básicas de Python que usaremos en el resto de las prácticas. En primer lugar observa que el texto está organizado en *celdillas interactivas*. Para añadir una celdilla nueva pincha en Insert y selecciona si la quieres añadir encima o debajo de la celdilla en la que está situado el cursor. La celdilla que se añade será una celdilla de tipo *Code* mientras que esta es de tipo *Markdown*. Para ejecutar una celdilla debes pulsar las teclas Shift+Enter o pinchar en ▶ Run

In [2]:
2+3

5

Las celdillas de código están numeradas como celdillas de entrada (con In[]) y sus correspondientes celdillas de salida (Out[]).

In [3]:
5*8

40

En las celdillas de texto podemos escribir en *cursiva*, en **negrita** o ~~tachado~~ entre otros.

## Variables y tipos de objetos

### Tipos fundamentales

La asignación de variables se hace utilizando el signo `=`. El tipado de variables es dinámico por lo que no hay que especificar el tipo de variable cuando la creamos.

In [1]:
a=3

In [4]:
type(a)

int

In [9]:
print(a)

12


In [10]:
a=a+3

In [11]:
a

15

In [13]:
b=12.5

In [14]:
type(b)

float

In [15]:
c= 2 + 3j #la unidad imaginaria se representa por j

In [16]:
type(c)

complex

In [ ]:
c.real

In [ ]:
c.imag

In [2]:
type(True) #Datos de tipo lógico

bool

Cuando escribimos por ejemplo print(2), Python hace lo siguiente:
- Crea un objeto entero y le asigna una identidad (número entero único).
- Guarda en ese objeto el valor 2.
- Llama a la función `print()` que lo muestra en pantalla.

In [3]:
print(2, id(2), type(2))

2 2357599562064 <class 'int'>


Los identificadores (nombres) que usamos para referirnos a los objetos
deben cumplir las cuatro siguientes condiciones:
- No contener espacios en blanco.
- Estar formados por letras, números o el carácter de guion bajo (_).
- No comenzar por un número.
- No pueden coincidir con palabras reservadas (las que tienen un significado concreto, ya definido, en el lenguaje):

    False, assert, continue, except, if, nonlocal, return, None, async, def, finally, import, not, try,
    True, await, del, for, in, or, while, and, break, elif, from, is, pass, with, as, class, else, global, lambda, raise, yield

### Operadores aritméticos

Los operadores aritméticos en Python son: `+`, `-`, `*`, `**`, `/`, `//`,`%`. Veamos unos ejemplos:

In [4]:
3+2,5*8.2

(5, 41.0)

In [ ]:
3**2 # potencia

In [ ]:
b/a

In [17]:
10//3 # división entera

3

In [ ]:
10%3 # módulo, resto de la división entera

Estos operadores aritméticos se pueden combinar con una asignación

In [ ]:
a=5

In [ ]:
a+=1 # hace a=a+1

In [ ]:
a

In [ ]:
b=7

In [ ]:
b/=2 # hace b=b/2
print(b)

Los operadores booleanos serán `and`, `not`, `or`.
Los operadores de comparación `>`, `<`, `>=` (mayor, menor, mayor o igual), `<=` (menor o igual), `==` igualdad, `is` identidad.

In [18]:
2 < 5, 2 > 5, 2 <= 5 

(True, False, True)

In [5]:
2 < 5 and 2 > 3

False

### Tipos compuestos: strings y listas

Las cadenas de caracteres (o **strings**) se utilizan para mensajes de texto. Estas cadenas de caracteres se escriben entre `' '` o entre `'' ''`

In [7]:
st='Métodos Numéricos I'

In [ ]:
type(st)

In [ ]:
st[0] # ¡Ojo! Se empieza a contar en 0

In [21]:
st[1:4]

'éto'

In [ ]:
st[:4]

In [ ]:
st[1:]

In [8]:
st[0:10:2] # el 2 corresponde al paso de salto

'MtdsN'

In [9]:
len(st)

19

In [22]:
print(2,'Hola',False,3.1416) # la sentencia print convierte todos los elementos en strings

2 Hola False 3.1416


In [23]:
# Se puede dar formato a un string tipo lenguaje C
s = "valor1 = %.3f. valor2 = %d" % (3.1415, 5.3)
print(s)

valor1 = 3.142. valor2 = 5


Las **listas** tienen un comportamiento similar a los strings pero sirven para almacenar datos de distinto tipo. Para crear una lista se utilizan corchetes `[ ]`

In [32]:
l=[1,3,5,7]

In [ ]:
print(type(l))
print(l)

In [ ]:
l[0]

In [33]:
l[1:]

[3, 5, 7]

In [ ]:
l[:2]

In [ ]:
l[::2] # paso 2

In [24]:
lio=[1, [4,3,2], 'Feliz']
lio

[1, [4, 3, 2], 'Feliz']

Se pueden crear listas utilizando funciones creadas para ello como la función `range`. En realidad, se genera un iterador que puede convertirse en lista utilizando la orden `list`. 

In [25]:
inicio=4
fin=20
paso=2
range(inicio, fin, paso)

range(4, 20, 2)

In [26]:
list(range(inicio, fin, paso))

[4, 6, 8, 10, 12, 14, 16, 18]

Se pueden añadir elementos a una lista usando `append`

In [ ]:
mi_lista=[] # se crea una lista vacía
mi_lista.append('L')
mi_lista.append('a')
mi_lista.append('d')
mi_lista

In [ ]:
mi_lista[1]='i' #cambia el elemento de la posición 1 de la lista por 'a'
mi_lista

In [ ]:
mi_lista.insert(1,'e') # inserta un elemento en una posición especificada 
mi_lista.insert(4,'o')
mi_lista

In [ ]:
mi_lista.remove('d') # elimina un elemento de la lista
mi_lista

In [10]:
del mi_lista[3] # elimina el elemento de la lista que está en la posición indicada
mi_lista

NameError: name 'mi_lista' is not defined

Las **tuplas** son parecidas a las listas salvo por el hecho de que son *inmutables*, es decir, no se pueden modificar una vez creadas. Se crean usando la sintáxis `(...,...,...)` o incluso sin paréntesis. 

In [27]:
a = (1,2,3)
print(a)
print(type(a))

(1, 2, 3)
<class 'tuple'>


Se pueden utilizar a veces para asignar varias variables a la vez:

In [28]:
x, y, z = a
print(x)


1


In [ ]:
max(1,2,3)

## Estructuras de control

### Condicionales: if, elif, else

Para introducir condicionales en Python usamos `if`, `elif` (else if) y `else`:

In [29]:
a = float(input('Dame un valor: '))
if a<0:
    print(a, ' es negativo')
elif a>0:
    print(a, ' es positivo')
else:
    print(a, ' es cero')

Dame un valor: 4
4.0  es positivo


**Ejercicio:** Escribe un pequeño programa que calcule el máximo entre 4 números que debe introducir el usuario sin utilizar la función `max` de Python.

###  Bucles

Los bucles pueden programarse de diferentes formas pero la más habitual es utilizando la sentencia `for`

In [30]:
for x in [3,5,7]:
    print(x)

3
5
7


In [34]:
for x in range(3):
    print(x)          # recordemos que range(n) recorre los números enteros de 0 a n-1

0
1
2


In [35]:
for x in range(-1,3):
    print(x)           # observa que range(a,b) recorre los números enteros de a a b-1

-1
0
1
2


A veces puede ser útil acceder a los índices de los valores de nuestra lista mientras iteramos sobre ella.

In [ ]:
for i,x in enumerate(range(-2,3)):
    print(i,x)

También se suele utilizar la orden `while`

In [ ]:
i=1
while i<= 3:
    print(i**2)
    i+=1
print('fin')

Es interesante el uso de listas como en este ejemplo:

In [ ]:
l=[x**2 for x in range(1,4)]
print(l)

### Funciones

En Python las funciones se definen mediante la palabra clave `def`, seguida del nombre de la funcion con sus correspondientes paréntesis y `:`. El código que sigue a continuación irá indentado y corresponderá al cuerpo de la función. 

En los paréntesis puede no aparecer ninguna variable:

In [ ]:
def l3():
    for i in range (3):
        print(i**3)

In [ ]:
l3()

O puede aparecer una variable como suele ser habitual en las funciones matemáticas:

In [31]:
def factorial(x):
    """
    Devuelve el factorial de un número x              
    
    """
    fact=1
    for i in range(2,x+1):
        fact*=i                                  ## la información comprendida entre las triples comillas
    print('El factorial de',x, 'es', fact)       ##  proporciona una documentación sobre el propósito de la función

In [32]:
factorial(5)

El factorial de 5 es 120


In [39]:
help(factorial)

Help on function factorial in module __main__:

factorial(x)
    Devuelve el factorial de un número x



En la propia definición de una función podemos dar valores por defecto a los argumentos de la función:

In [ ]:
def potencia(x,n=2):
    print(x**n)

In [ ]:
potencia(2)

In [ ]:
potencia(2,3)

In [ ]:
potencia(3,2)

In [ ]:
potencia(x=2,n=3)

In [ ]:
potencia(n=3,x=2)

Observa que si proporcionamos de manera explícita el nombre de los argumentos en la correspondiente llamada a la función, entonces ni siquiera es necesario que éstos vengan en el mismo orden en el que se definió la función.

## Librerías

Vamos a utilizar diferentes librerías de Python según el tipo de programas o funciones que vayamos a tratar. Dos de las más importantes para nosotros serán `NumPy`, `Scipy`, `SymPy` y `MatPlotlib`. Hay diferentes formas de cargar esas librerías, podéis documentaros un poco sobre este asunto. Nosotros normalmente lo haremos utilizando un pseudónimo que es lo más habitual.

In [12]:
import numpy as np              # aquí cargamos numpy con el pseudónimo np               
import sympy as sp              # y sympy  como sp
import matplotlib.pyplot as plt  # Aquí cargamos el módulo pyplot de la librería MatPlotlib 

La librería `NumPy` es una librería especializada en el cálculo numérico y el análisis de datos. `Sympy`se utiliza para el cálculo simbólico y el módulo `PyPlot` de la librería `MatPlotlib` para la representación gráfica.

Cuando utilizamos alguna función de alguna de esas librerías tendremos que escribir delante el pseudónimo como en el siguiente ejemplo:

In [ ]:
x=sp.Symbol('x') # nos permite usar x de forma simbólica, como un símbolo

In [ ]:
x**2

In [ ]:
np.array([1,2,3])

In [ ]:
np.arange(0,10,2) 

Hemos creado un **array** de dos formas diferentes. Los arrays de NumPy son objetos mutables igual que las listas de Python pero existen algunas diferencias entre ellos. En las listas no se pueden realizar operaciones matemáticas mientras que sí es posible en los arrays. Por otro lado, las listas permiten trabajar con diferentes tipos de datos, incluso listas anidadas.

In [ ]:
l=[1,2,3]

In [ ]:
2*l

In [20]:
mat=np.array([[1,2,3],[4,5,6]])

In [ ]:
2*mat

In [29]:
mat.shape[0]

2

In [16]:
mat.size

6

In [17]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.amax(mat), np.argmax(mat) # para calcular el máximo en un array y la posición que ocupa dentro del array

In [ ]:
np.amax(mat[0])

In [19]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
np.zeros([2,4]) # crea un array de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3) # crea un array de unos

In [21]:
np.linspace(2,3,10) # crea un array con 10 elementos equiespaciados entre 2 y 3 (ambos incluidos)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [ ]:
np.eye(4) # crea la matriz identidad de orden 4

In [ ]:
np.diag([2,-3,5]) # crea una matriz diagonal introduciendo los elementos de la diagonal principal 

In [27]:
np.random.rand(2,3) # crea un array de dos filas y tres columnas de números aleatorios entre o y 1

array([[0.76846056, 0.7368112 , 0.69139501],
       [0.86355916, 0.68482072, 0.65180286]])

In [22]:
a=np.array([i**2 for i in range(3)])
a

array([0, 1, 4])

In [24]:
b=np.array([[i**2+j for j in range(3)] for i in range(2)])
b

array([[0, 1, 2],
       [1, 2, 3]])

In [25]:
n=3
b[:,:n-1]

array([[0, 1],
       [1, 2]])

In [26]:
np.dot(b,a) 

array([ 9, 14])

**Ejercicio:** 

- Crea un array de `Numpy` de 10 filas y 9 columnas de manera que el elemento $(i,j)$ sea  $\frac{1}{i+j-1}$ para $1\le i\le 10$ y $1\le j\le 9$. Ten en cuenta que las filas y columnas se numeran a partir de 1 pero en Python la numeración empieza en 0. El primer elemento del array debe ser 1.

- Crea ahora un array $B$ de números aleatorios entre 0 y 3 de tamaño $5\times 5$. Calcula $B^{8}$.