<h1><b>Título: Notebook de introducción a Numpy</b></h1>

<b>Autor: </b><i>Manuel Pegalajar Cuéllar</i>

<b>Asignatura:</b> Aprendizaje Automático

<center><img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg"/></center>



# **Creación de arrays con NumPy**

Existen diversas formas de crear un objeto *ndarray* con numpy. Por ejemplo:

In [13]:
import numpy as np # Importar la biblioteca

# Creación de array 1-D desde lista, tipo float
arr_fl= np.array([1, 2, 3, 4, 5, 6], dtype=float)
print('Array float: \n{}'.format(arr_fl))
print('El array tiene {} dimensiones, con un total de {} componentes repartidas con la forma {}'.format(arr_fl.ndim, arr_fl.size, arr_fl.shape))

# Creación de array 2-D desde lista, tipo float
arr_fl= np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print('\nArray float: \n{}'.format(arr_fl))
print('El array tiene {} dimensiones, con un total de {} componentes repartidas con la forma {}'.format(arr_fl.ndim, arr_fl.size, arr_fl.shape))


# Array 3-D de ceros con tamaño (2, 3, 4)
arr_ceros= np.zeros((2, 3, 4))
print('\nArray de ceros: \n{}'.format(arr_ceros))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_ceros.ndim, arr_ceros.dtype, arr_ceros.size, arr_ceros.shape))

# Array 3-D de unos con tamaño (2, 3, 4)
arr_unos= np.ones((2, 3, 4))
print('\nArray de unos: \n{}'.format(arr_unos))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_unos.ndim, arr_unos.dtype, arr_unos.size, arr_unos.shape))


# Array 1-D vacío de 5 componentes
arr_vacio= np.empty( 5 )
print('\nArray "vacio" (sin inicializar): \n{}'.format(arr_vacio))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_vacio.ndim, arr_vacio.dtype, arr_vacio.size, arr_vacio.shape))

# Array 1-D con componentes entre 0 y 1 de 0.1 en 0.1 (sin incluir el 1)
arr_range= np.arange(0, 1, 0.1)
print('\nArray de rango: \n{}'.format(arr_range))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_range.ndim, arr_range.dtype, arr_range.size, arr_range.shape))

# Array 1-D con 11 componentes complejas entre -1 y 1 ambos incluidos, espaciadas uniformemente
arr_lin= np.linspace(start= -1, stop= 1, num=11, dtype= complex)
print('\nArray lineal: \n{}'.format(arr_lin))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_lin.ndim, arr_lin.dtype, arr_lin.size, arr_lin.shape))


# Array 2-D diagonal a 1, de 3 filas y 4 columnas
arr_eye= np.eye(3, 4)
print('\nArray eye: \n{}'.format(arr_eye))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_eye.ndim, arr_eye.dtype, arr_eye.size, arr_eye.shape))


# Array 2-D diagonal (matriz cuadrada) con diagonal igual a elementos en lista
arr_diag= np.diag( [1, 2, 3, 4] )
print('\nArray diag: \n{}'.format(arr_diag))
print('El array tiene {} dimensiones de tipo {}, con un total de {} componentes repartidas con la forma {}'.format(arr_diag.ndim, arr_diag.dtype, arr_diag.size, arr_diag.shape))

Array float: 
[1. 2. 3. 4. 5. 6.]
El array tiene 1 dimensiones, con un total de 6 componentes repartidas con la forma (6,)

Array float: 
[[1. 2. 3.]
 [4. 5. 6.]]
El array tiene 2 dimensiones, con un total de 6 componentes repartidas con la forma (2, 3)

Array de ceros: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
El array tiene 3 dimensiones de tipo float64, con un total de 24 componentes repartidas con la forma (2, 3, 4)

Array de unos: 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
El array tiene 3 dimensiones de tipo float64, con un total de 24 componentes repartidas con la forma (2, 3, 4)

Array "vacio" (sin inicializar): 
[0.   0.25 0.5  0.75 1.  ]
El array tiene 1 dimensiones de tipo float64, con un total de 5 componentes repartidas con la forma (5,)

Array de rango: 
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
El array tiene 1 dimensiones de tipo float64, con un total de 

## Conversión de tipos en un *ndarray*

Se utiliza el método **astype(tipo)**, donde **tipo** es el tipo de dato destino. Se genera un nuevo *ndarray*. Por ejemplo:

In [15]:
import numpy as np

a= np.array([1, 2, 3], dtype=float)
print('El tipo de las componentes de a es: {}'.format(a.dtype))

# Conversión a entero
b= a.astype(int)
print('El tipo de las componentes de b es: {}'.format(b.dtype))

El tipo de las componentes de a es: float64
El tipo de las componentes de b es: int64


## **CUIDADO CON LAS REFERENCIAS**. Copia de arrays.

Los objetos **ndarray** creados son referencias. una asignación típica **a= b** hace que la variable **a** apunte **al mismo objeto de la variable b**.

In [17]:
import numpy as np

b= np.array([1, 2, 3, 4, 5, 6])
a= b

a[0]= 20
print('El array a:\n{}'.format(a))
print('El array b:\n{}'.format(b))

# FORMA CORRECTA DE HACER UNA COPIA:
a= b.copy()
a[0]= 1
print('El array a:\n{}'.format(a))
print('El array b:\n{}'.format(b))


El array a:
[20  2  3  4  5  6]
El array b:
[20  2  3  4  5  6]
El array a:
[1 2 3 4 5 6]
El array b:
[20  2  3  4  5  6]


# **Indexación y acceso a componentes**

Diferentes formas de acceso a componentes, más allá de la indexación propia de Python en listas:


In [37]:
arr1d= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2d= np.array([ [1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]
                ])

# Indexación por rango
print('arrid: \n{}'.format(arr1d))
print('Componentes pares de arr1d:\n{}'.format( arr1d[::2] ))
print('Componentes impares de arr1d:\n{}'.format( arr1d[1::2] ))

print('\narr2d: \n{}'.format(arr2d))
print('Componentes pares de arr2d (OJO: SOLO FILAS):\n{}'.format( arr2d[::2] ))
print('Componentes impares de arr2d (OJO: SOLO COLUMNAS):\n{}'.format( arr2d[:, 1::2] ))
print('Componentes filas pares y columnas impares de arr2d:\n{}'.format( arr2d[::2, 1::2] ))

# Indexación por tuplas de índices
print('Filas (2, 1, 1, 0) de arr2d):\n{}'.format( arr2d[(2, 1, 1, 0), :] ))
print('Componentes (0, 2) y (1, 3):\n{}'.format( arr2d[(0, 1), (2, 3)] ))

# Indexación booleana
pares= arr2d[ arr2d%2 == 0 ]
print('Elementos pares de arr2d: \n{}'.format(pares))

seleccion= arr2d[:, 0]%3<=1
print('Filas donde la primera columna %3 e<= 1:\n{}'.format(seleccion))
filas_seleccion= arr2d[seleccion]
print('Seleccion de filas donde la primera columna %3 es 1:\n{}'.format(filas_seleccion))

# Busqueda de elementos con where
posiciones_a_buscar= np.where( arr2d>=7 )
print('Indices donde las componentes de arr2d >= 7: \n{}', posiciones_a_buscar)
print('Elementos >=7 de arr2: \n{}'.format(arr2d[posiciones_a_buscar[0], posiciones_a_buscar[1]]))

arrid: 
[1 2 3 4 5 6 7 8 9 0]
Componentes pares de arr1d:
[1 3 5 7 9]
Componentes impares de arr1d:
[2 4 6 8 0]

arr2d: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Componentes pares de arr2d (OJO: SOLO FILAS):
[[ 1  2  3  4]
 [ 9 10 11 12]]
Componentes impares de arr2d (OJO: SOLO COLUMNAS):
[[ 2  4]
 [ 6  8]
 [10 12]]
Componentes filas pares y columnas impares de arr2d:
[[ 2  4]
 [10 12]]
Filas (2, 1, 1, 0) de arr2d):
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Componentes (0, 2) y (1, 3):
[3 8]
Elementos pares de arr2d: 
[ 2  4  6  8 10 12]
Filas donde la primera columna %3 e<= 1:
[ True False  True]
Seleccion de filas donde la primera columna %3 es 1:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Indices donde las componentes de arr2d >= 7: 
{} (array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))
Elementos >=7 de arr2: 
[ 7  8  9 10 11 12]


## Eliminar elementos repetidos

NumPy dispone de la función **unique**, muy útil para eliminar elementos repetidos de un array (el resultado debe ser un array 1D). Un ejemplo:


In [134]:
import numpy as np

a= np.array([ [1, 2, 3],
              [2, 3, 4],
              [3, 4, 5]
            ])
print('Array original:\n{}'.format(a))

# Elementos de a sin repetir
unicos= np.unique(a)
print('Los elementos del array original sin repetir son:\n{}'.format(unicos))

Array original:
[[1 2 3]
 [2 3 4]
 [3 4 5]]
Los elementos del array original sin repetir son:
[1 2 3 4 5]


# **Cambio de forma**

Es habitual cambiar la forma de un array o la disposición de sus elementos para poder operar más cómodamente con ellos. Funciones como **reshape**, **squeeze**, **vstack** o **hstack**, **swapaxes** o **newaxis** cumplen con este cometido fácilmente.

In [45]:
import numpy as np

arr1d= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print('arr1d:\n{}'.format(arr1d))

# Creación de array 2d con 2 filas y el número de columnas que corresponda
arr2d= arr1d.reshape(2, -1)
print('arr2d desde arr1d con reshape:\n{}'.format(arr2d))

# Intercambio de ejes de la dimensión 0 y de la 1
arr2d= arr2d.swapaxes(0, 1)
print('arr2d con ejes intercambiados con swapaxes:\n{}'.format(arr2d))


# Intercambio de ejes de la dimensión 0 y de la 1
arr3d= arr2d[:, np.newaxis]
print('arr3d insertando un nuevo eje vacío al final:\n{}'.format(arr3d))

# Eliminar ejes inútiles
arr2d= arr3d.squeeze()
print('arr2d desde arr3d con un eje vacío (sin uso):\n{}'.format(arr2d))

# Concatenación de arrays
arr1d_extended= np.concatenate((arr1d, arr1d))
print('Concatenación de arr1d consigo mismo: \n{}'.format(arr1d_extended))

arr2d_h_extended= np.hstack((arr2d, arr2d))
print('Concatenación de arr2d consigo mismo en horizontal: \n{}'.format(arr2d_h_extended))

arr2d_v_extended= np.vstack((arr2d, arr2d))
print('Concatenación de arr2d consigo mismo en vertical: \n{}'.format(arr2d_v_extended))


arr1d:
[1 2 3 4 5 6 7 8 9 0]
arr2d desde arr1d con reshape:
[[1 2 3 4 5]
 [6 7 8 9 0]]
arr2d con ejes intercambiados con swapaxes:
[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
arr3d insertando un nuevo eje vacío al final:
[[[1 6]]

 [[2 7]]

 [[3 8]]

 [[4 9]]

 [[5 0]]]
arr2d desde arr3d con un eje vacío (sin uso):
[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
Concatenación de arr1d consigo mismo: 
[1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0]
Concatenación de arr2d consigo mismo en horizontal: 
[[1 6 1 6]
 [2 7 2 7]
 [3 8 3 8]
 [4 9 4 9]
 [5 0 5 0]]
Concatenación de arr2d consigo mismo en vertical: 
[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]
 [1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]


# **Operadores básicos**

Todos los operadores de NumPy se pueden aplicar sobre tipo *ndarray* (componente a componente) + sobre datos escalares. Por ejemplo:

In [46]:
import numpy as np

a= np.array([1, 2, 3])
b= np.array([4, 5, 6])
print('a: \n{} \nb: \n{}'.format(a,b))

# Operadores aritméticos
print('Suma de a+b: {}'.format( a+b ))
print('Suma de a+1: {}'.format( a+1 ))
print('Multiplica a*b: {}'.format( a*b ))
print('Eleva a**b: {}'.format( a**b ))
print('Divide a/b: {}'.format( a/b ))

a: 
[1 2 3] 
b: 
[4 5 6]
Suma de a+b: [5 7 9]
Suma de a+1: [2 3 4]
Multiplica a*b: [ 4 10 18]
Eleva a**b: [  1  32 729]
Divide a/b: [0.25 0.4  0.5 ]


### Funciones para cálculo de valores booleanos

Disponemos también de funciones para verificar el valor booleano de un array en alguna o en todas sus componentes mediante **np.any()** y **np.all()**, respectivamente. También hay otras que extienden a Python, como **isin** para **in**. etc. Por ejemplo:

In [144]:
import numpy as np

a= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print('Array inicial: {}'.format(a))

# Seleccion de las componentes que son <=3
b= a<=3
print('Las componentes que son <=3: {}'.format(b))

#uso de any
sol= np.any(b)
print('¿Hay alguna componente que cumple la condición? {}'.format(sol))

#uso de all
sol= np.all(b)
print('¿Absolutamente todas las componentes cumplen la condición? {}'.format(sol))


#uso de isin
sol= np.isin(a, (1,2))
print('¿Algún valor en el conjunto (1,2)? {}'.format(sol))

Array inicial: [1 2 3 4 5 6 7 8 9 0]
Las componentes que son <=3: [ True  True  True False False False False False False  True]
¿Hay alguna componente que cumple la condición? True
¿Absolutamente todas las componentes cumplen la condición? False
¿Algún valor en el conjunto (1,2)? [ True  True False False False False False False False False]


## Funciones matemáticas

En Nympy disponemos de todas las funciones matemáticas de **math** (y muchas más). Se aplican a los arrays componente a componente:

In [ ]:
import numpy as np

a= np.array([1, 2, 3])
print('a: \n{}'.format(a))

# Operadores aritméticos
print('sqrt(a): {}'.format( np.sqrt(a) ))
print('exp(a): {}'.format( np.exp(a) ))
print('cos(a): {}'.format( np.cos(a) ))
print('... y un largo etc')
print('Multiplica a*b: {}'.format( a*b ))
print('Eleva a**b: {}'.format( a**b ))
print('Divide a/b: {}'.format( a/b ))

## Constantes matemáticas

También disponemos de las constantes y símbolos matemáticos más conocidos y usuales: $\pi$, $e$, $\infty$...

In [47]:
import numpy as np

print('El número pi: {}'.format(np.pi))
print('El número e: {}'.format(np.e))
print('Infinito positivo: {}'.format(np.inf))
print('Infinito negativo: {}'.format(-np.inf))

El número pi: 3.141592653589793
El número e: 2.718281828459045
Infinito positivo: inf
Infinito negativo: -inf


De especial interés es la constante **nan**, que se utiliza cuando un valor no puede ser calculado, es desconocido, no es representable... (similar a **None** en Python, aunque con significados muy distintos). Por ejemplo:


In [60]:

# Array de datos con valores perdidos o desconocidos
a = np.array([2, np.nan, 4, 1, np.nan])
print('Array con valores perdidos: {}'.format(a))

valores_nan= np.isnan(a)
print('Componentes con valor nan: {}'.format(valores_nan))
print('¿Hay algún valor nan? {}'.format(np.any(valores_nan)))
print('¿En qué índices están los valores nan?: {}'.format( np.where( valores_nan )[0] ))


Array con valores perdidos: [ 2. nan  4.  1. nan]
Componentes con valor nan: [False  True False False  True]
¿Hay algún valor nan? True
¿En qué índices están los valores nan?: [1 4]


# **Operaciones con vectores**

En NumPy podemos tratar un objeto *ndarray* como si fuera un vector. Por tanto, podemos aplicar operaciones sobre vectores tales como el producto escalar, producto cruz, etc.

Un ejemplo:

In [77]:
import numpy as np

# Definición de vectores
v1= np.array([1, 2])
v2= np.array([3, 4])
print('Vector v1:\n{}'.format(v1))
print('Vector v2:\n{}'.format(v1))

# Norma de un vector
print('La norma de v1 es {} y la de v2 es {}'.format( np.linalg.norm(v1), np.linalg.norm(v2) ))

# Producto escalar
print('El producto escalar <v1,v2> es: {}'.format(np.dot(v1, v2)))

# Producto cruz
v1= np.concatenate((v1, [0]))
v2= np.concatenate((v2, [0]))
print('v1 en 3D: {}'.format(v1))
print('v2 en 3D: {}'.format(v2))
print('El producto cruz v1 x v2 es: \n{}'.format(np.cross(v1, v2)))

Vector v1:
[1 2]
Vector v2:
[1 2]
La norma de v1 es 2.23606797749979 y la de v2 es 5.0
El producto escalar <v1,v2> es: 11
v1 en 3D: [1 2 0]
v2 en 3D: [3 4 0]
El producto cruz v1 x v2 es: 
[ 0  0 -2]


# **Operadores con matrices**

Una de las ventajas principales de NumPy en la asignatura reside en el uso de operadores sobre matrices, incluyendo funcionalidades propias del álgebra lineal en el paquete **np.linalg**. Veamos algunos ejemplos:


In [73]:
import numpy as np

a= np.array([1, 2, 3, 5, 6, 7]).reshape(2, -1)
print('Matriz a:\n{}'.format(a))
b= np.array([1, 2, 3, 5, 6, 7]).reshape(3, -1)
print('Matriz b:\n{}'.format(b))

# Cálculo de la traspuesta de una matriz
print('La traspuesta de a es: \n{}'.format(a.transpose()))
print('La traspuesta de a es: \n{}'.format(a.T))

# suma/resta de matrices
print('a+b^t= \n{}'.format(a + b.T))

# Multiplicación de matrices
print('a*b:\n{}'.format( a @ b ))
print('a*b:\n{}'.format( np.matmul(a , b ))) # Util para hacer multiplicación encadenada de más de dos matrices


# Determinante de a*b
print('Determinante de a*b: {}'.format(np.linalg.det(a@b)))

# Matriz inversa de a*b
print('Inversa (a*b)^(-1): \n{}'.format(np.linalg.inv(a@b)))

# Valores y vectores propios de a*b
eig_val, eig_vec= np.linalg.eig(a@b)
print('Vectores propios de a*b:\n{}'.format(eig_vec))
print('... con valores propios respectivos: \n{}'.format(eig_val))


Matriz a:
[[1 2 3]
 [5 6 7]]
Matriz b:
[[1 2]
 [3 5]
 [6 7]]
La traspuesta de a es: 
[[1 5]
 [2 6]
 [3 7]]
La traspuesta de a es: 
[[1 5]
 [2 6]
 [3 7]]
a+b^t= 
[[ 2  5  9]
 [ 7 11 14]]
a*b:
[[25 33]
 [65 89]]
a*b:
[[25 33]
 [65 89]]
Determinante de a*b: 80.00000000000018
Inversa (a*b)^(-1): 
[[ 1.1125 -0.4125]
 [-0.8125  0.3125]]
Vectores propios de a*b:
[[-0.80531119 -0.35009824]
 [ 0.59285233 -0.93671299]]
... con valores propios respectivos: 
[  0.70612822 113.29387178]


# **Estadística básica**

Una de las mayores facilidades de NumPy a la hora de trabajar con conjuntos de datos reside en la simplicidad para aplicar funcionalidades de estadística descriptiva básica, creando sumas, productos, cálculo de medias y desviaciones típicas, máximos, mínimos...

Un ejemplo:

In [84]:
import numpy as np

a= np.array([1, 2, 3, 5, 6, 7, 1])
print('Array 1D: {}'.format(a))

print('Suma de componentes: {}'.format(np.sum(a)))
print('Suma ACUMULADA de componentes: {}'.format(np.cumsum(a)))
print('Media de componentes: {}'.format(np.mean(a)))
print('Mediana de componentes: {}'.format(np.median(a)))
print('Desviación estándar de componentes: {}'.format(np.std(a)))
print('Varianza de componentes: {}'.format(np.var(a)))
print('Valor mínimo: {} y su posición en el array: {}'.format(np.min(a), np.argmin(a)))
print('Valor máximo: {} y su posición en el array: {}'.format(np.max(a), np.argmax(a)))


Array 1D: [1 2 3 5 6 7 1]
Suma de componentes: 25
Suma ACUMULADA de componentes: [ 1  3  6 11 17 24 25]
Media de componentes: 3.5714285714285716
Mediana de componentes: 3.0
Desviación estándar de componentes: 2.2587697572631282
Varianza de componentes: 5.1020408163265305
Valor mínimo: 1 y su posición en el array: 0
Valor máximo: 7 y su posición en el array: 5


# **Números aleatorios y probabilidad**

NumPy también permite generar números aleatorios de diferentes distribuciones de probabilidad. Incorpora el paquete **np.random** para agrupar todas las funcionalidades. Por ejemplo:

In [92]:
import numpy as np

# Inicializa semilla de números aleatorios
# Es una función útil para favorecer reproducibilidad de experimentos
np.random.seed(1234)

# generación de array aleatorio en U(0,1)
a= np.random.rand(2, 3)
print('Matriz de 2x3 aleatoria U(0,1): \n{}'.format(a))

# generación de array aleatorio en N(0,1)
a= np.random.randn(3, 2)
print('\nMatriz de 3x2 aleatoria N(0,1): \n{}'.format(a))

# Generación de distribución de probabilidad discreta uniforme
n= 4 # 4 valores de probabilidad
valores= ['blanco', 'azul', 'verde', 'amarillo'] # Valores de variable aleatoria
prob_dist= np.ones(n)/n # Distribución de probabilidad

# Seleccionamos 3 valores aleatorios
np.random.seed(1234)
muestra= np.random.choice(a= valores, size= 3, p= prob_dist)
print('Se han seleccionado los valores: {}'.format(muestra))

# Igual pero se devuelve un entero
np.random.seed(1234)
muestra= np.random.choice(len(prob_dist), size= 3, p= prob_dist)
print('Se han seleccionado los valores: {}'.format(muestra))

# Generación de enteros aleatorios
enteros= np.random.randint(low= 0, high= 10, size=50)
print('50 enteros aleatorios entre 0 y 9: {}'.format(enteros))

# Generación de permutaciones aleatorias
permutacion= np.random.permutation(5)
print('Permutación de 5 elementos: {}'.format(permutacion))


Matriz de 2x3 aleatoria U(0,1): 
[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]]

Matriz de 3x2 aleatoria N(0,1): 
[[ 0.85958841 -0.6365235 ]
 [ 0.01569637 -2.24268495]
 [ 1.15003572  0.99194602]]
Se han seleccionado los valores: ['blanco' 'verde' 'azul']
Se han seleccionado los valores: [0 2 1]
50 enteros aleatorios entre 0 y 9: [8 9 1 7 9 6 8 0 5 0 9 6 2 0 5 2 6 3 7 0 9 0 3 2 3 1 3 1 3 7 1 7 4 0 5 1 5
 9 9 4 0 9 8 8 6 8 6 3 1 2]
Permutación de 5 elementos: [4 0 3 1 2]


# **E/S externa**

NumPy también permite guardar datos a fichero y leer datos desde fichero, aunque a un nivel muy básico. Lo normal (ideal) es guardar los datos en formato binario de NumPy (**extensión .npy + .npz**) de modo que se puedan cargar posteriormente de forma más rápida, aunque se permite también la escritura/lectura de ficheros de texto.


## Ejemplo de escritura y lectura en formato binario **.npz**

Se puede usar la función **save** para guardar un array (extensión **.npy**), y también la funzión **savez** para guardar múltiples arrays (extensión **.npz**).

La función **savez** guarda los datos en binario en formato **diccionario**. A la hora de ejecutar la función es necesario proporcionarle tanto la clave como el valor para cada array a guardar.

In [112]:
import numpy as np

# Creación de dos arrays arbitrarios
a= np.array([1, 2, 3])
b= np.array([3, 4, 5, 6]).reshape(2, 2)
print('Array a inicial:\n{}'.format(a))
print('Array b inicial:\n{}'.format(b))

# Guardar a fichero ejemplo
np.savez('ejemplo.npz', vector=a, matriz=b) # Se guarda como diccionario

# Cambiamos valores para probar
a,b= 'hola', 'adios'
print('Ahora a vale \n{} \ny b vale \n{}'.format(a,b))


# Cargamos el fichero
valores= np.load('ejemplo.npz') # Se carga como diccionario
print('Valores leídos desde fichero (diccionario): ', valores)

# Coger valores desde diccionario
a= valores['vector']
b= valores['matriz']
print('Lectura de fichero. Ahora a vale \n{} \ny b vale \n{}'.format(a,b))

Array a inicial:
[1 2 3]
Array b inicial:
[[3 4]
 [5 6]]
Ahora a vale 
hola 
y b vale 
adios
Valores leídos desde fichero (diccionario):  NpzFile 'ejemplo.npz' with keys: vector, matriz
Lectura de fichero. Ahora a vale 
[1 2 3] 
y b vale 
[[3 4]
 [5 6]]


## Ejemplo de escritura/lectura en formato de texto


Una forma más estandarizada de guardar datos es en ficheros de texto, que posteriormente pueden cargarse desde cualquier otro sistema. Se permite incluir, además, separadores que permitan identificar dónde comienza una celda y dónde termina otra.

Veamos un ejemplo:

In [143]:
import numpy as np

# Datos de la función XOR
xor= [['X', 'Y', 'SALIDA'], # Cabecera: entradas X,Y. Salidas: SALIDA
      ['Falso', 'Negativo', 'NO'], # (entrada falso, falso. salida: no)
      ['Falso', 'Positivo', 'SI'], # (entrada falso, cierto. salida: si)
      ['Cierto', 'Negativo', 'SI'], # (entrada cierto, falso. salida: si)
      ['Cierto', 'Positivo', 'NO'] # (entrada cierto, cierto. salida: no)
     ]

xor_data= np.array(xor, dtype=str)
print('dataset del XOR (tipo {}):\n{}'.format(xor_data.dtype, xor_data))


# Un ejemplo práctico del uso de unique:
print('---\nAnálisis del dominio:\n')
for i in range(len(xor_data[0])):
  print('El dominio de {} es: {}'.format(xor_data[0, i], np.unique(xor_data[1:, i])))
print('---\n')

# guardar a fichero de texto con delimitador coma
np.savetxt('xor.txt', xor_data, delimiter=',', fmt="%s")

# Apertura del fichero raw con Python
with open('xor.txt', 'r') as f:
  lineas= f.readlines()
print('Contenido leído desde el fichero:\n{}'.format(lineas))
# Mostrar cada línea
for i, linea in enumerate(lineas):
  print('Línea {}: {}'.format(i, linea))

# Apertura del fichero con NumPy
xor_loaded= np.loadtxt('xor.txt', delimiter=',', dtype='str')
print('\nCarga de fichero desde NumPy:\n{}'.format(xor_loaded))

# Transformar a datos numéricos
xor_loaded[ np.isin(xor_loaded, ('Falso', 'Negativo', 'NO'))]= 0
xor_loaded[ np.isin(xor_loaded, ('Cierto', 'Positivo', 'SI'))]= 1
print('Datos semitransformados a números (aún son cadenas con tipo {}):\n{}'.format(xor_loaded.dtype, xor_loaded))

xor_int= xor_loaded[1:, :].astype(int)
print('Ahora sólo los datos, de tipo {}:\n{}'.format(xor_int.dtype, xor_int))

dataset del XOR (tipo <U8):
[['X' 'Y' 'SALIDA']
 ['Falso' 'Negativo' 'NO']
 ['Falso' 'Positivo' 'SI']
 ['Cierto' 'Negativo' 'SI']
 ['Cierto' 'Positivo' 'NO']]
---
Análisis del dominio:

El dominio de X es: ['Cierto' 'Falso']
El dominio de Y es: ['Negativo' 'Positivo']
El dominio de SALIDA es: ['NO' 'SI']
---

Contenido leído desde el fichero:
['X,Y,SALIDA\n', 'Falso,Negativo,NO\n', 'Falso,Positivo,SI\n', 'Cierto,Negativo,SI\n', 'Cierto,Positivo,NO\n']
Línea 0: X,Y,SALIDA

Línea 1: Falso,Negativo,NO

Línea 2: Falso,Positivo,SI

Línea 3: Cierto,Negativo,SI

Línea 4: Cierto,Positivo,NO


Carga de fichero desde NumPy:
[['X' 'Y' 'SALIDA']
 ['Falso' 'Negativo' 'NO']
 ['Falso' 'Positivo' 'SI']
 ['Cierto' 'Negativo' 'SI']
 ['Cierto' 'Positivo' 'NO']]
Datos semitransformados a números (aún son cadenas con tipo <U8):
[['X' 'Y' 'SALIDA']
 ['0' '0' '0']
 ['0' '1' '1']
 ['1' '0' '1']
 ['1' '1' '0']]
Ahora sólo los datos, de tipo int64:
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


# **Ejercicios**

# Ejercicio 1:

Escribe el código que permita generar un array ``matriz`` tal que, al escribir ``print(matriz[2:,1:])`` se muestre el siguiente array numPy:

```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [ ]:
# Solución

## Ejercicio 2:

Para la matriz ``matriz`` generada en el ejercicio anterior, proporcionar por consola:

- La suma de todas sus componentes
- La suma de todas sus filas
- La suma de todas sus columnas

Para ello haga uso de la función **sum** cambiando, en el caso de ser necesario, el argumento **axis**.

In [ ]:
# Solución

## Ejercicio 3:

Suponga un experimento de una variable aleatoria $X$ en el que se lanza una moneda. Los posibles valores de la variable aleatoria son ``cara`` y ``cruz```, con probabilidades $p(X=CARA)=0.25$ y $p(X=CRUZ)=0.75$ (obviamente, la moneda está trucada).

Realice un total de $n=100$ experimentos (tomar 100 muestras) y, haciendo uso de la función **np.sum** -entre otras-, muestre el número de veces que se ha obtenido ``cara`` y el número de veces que se ha obtenido  ``cruz``.

## Ejercicio 4

Para la matriz siguiente, calcule sus vectores y valores propios:

$M=\begin{pmatrix}1 & 0\\0 & -1\end{pmatrix}$

# Solución

## Ejercicio 5

- Genere un total de 10000 valores aleatorios con la función ``randn``. Muestre su media y desviación típica.
- Genere un total de 10000 valores aleatorios con la función ``rand``. Muestre su media y desviación típica.

In [ ]:
# Solución

## Ejercicio 6

Visite la web <a href="https://www.geogebra.org/m/cF7RwK3H">https://www.geogebra.org/m/cF7RwK3H</a> para conocer un método estadístico para aproximar el valor de la constante $\pi$. Implemente desde cero un programa en Python que permita aproximar esta constante utilizando el método de Monte-Carlo descrito en la web, **utilizando NumPy de forma eficiente**.

In [ ]:
# Solución

# Ejercicio 7

Sean dos arrays $w=(w_0, w_1, ..., w_{n-1})$ y $x=(x_0, x_1, ..., x_{n-1})$, para un valor de $n$ arbitrario. Cree una función Python que permita calcular la salida $f(S)$ dada por las siguientes fórmulas, utilizando NumPy de la forma más eficiente posible:

$S= \sum_{i=0}^{n-1} w_ix_i$

$f(S)= {1\over{1+e^{-S}}}$

Las entradas a la función son $w$ y $x$.

In [ ]:
# Solución

## Ejercicio 8

Sea un array $x=(x_0, x_1, ..., x_{n-1})$, una matriz $W_{m, n}$ (donde $w_{i,j}$ sería la entrada de la fila $i$, columna $j$) y otro array $b=(b_0, b_1, ..., b_m)$. Implemente una función Python que utilice NumPy **sobre matrices** de forma eficiente para calcular un array $o=(o_1, o_2, ..., o_m)$ donde cada elemento se calcula como:

$o_i= max\{0, b_i + \sum_{j=0}^{n-1} w_{i,j}x_j \}$

Las entradas a la función son $W$, $b$ y $x$.

In [ ]:
# Solución