# <h1><b>Título: Notebook de introducción al tratamiento de datos con Scikit-Learn</b></h1>

<b>Autor: </b><i>Manuel Pegalajar Cuéllar</i>

<b>Asignatura:</b> Aprendizaje Automático


<center><img src="https://pypi-camo.freetls.fastly.net/b86b2758380b6bc7cbdf4ff97fda9826a3b74aa2/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f7363696b69742d6c6561726e2f7363696b69742d6c6561726e2f6d61696e2f646f632f6c6f676f732f7363696b69742d6c6561726e2d6c6f676f2e706e67"/></center>

# **Codificación de datos**

Los métodos de aprendizaje automático suelen trabajar sobre datos numéricos. Varios tipos:


- **Codificación real**: variables numéricas continuas
- **Codificación binaria**: Valores enteros 0/1
- **Codificación entera**: Valores enteros (guardan un orden)
- **Codificación One-Hot**: Codificación como array binario con un único 1.


Sin embargo, en ocasiones nos encontramos con que el conjunto de datos tiene valores de diferentes tipos:

- **Valores reales** (continuos).
- **Valores categóricos** (género, color, ...)
- **Valores de verdad** (sí/no, cierto/falso, ...)
- **Valores ordinales** (1, 2, 5, 4, 27...)


En ocasiones es necesario realizar transformaciones que permitan representar el conjunto de datos en un formato adecuado para su procesamiento.

Los mecanismos para codificación de datos se encuentran en **sklearn.preprocessing**:

- **LabelEncoder**: Se utiliza para transformar datos categóricos de una variable objetivo a predecir a valores ordinales.
- **OrdinalEncoder**: Similar a **LabelEncoder**. Se usa para transformar atributos (variables predictoras) a valores ordinales.
- **OneHotEncoder**: Transforma datos categóricos a arrays binarios con una única componente a 1 (el resto a 0).


Para ver todas las posibilidades de codificación (discretización, binarización, etc.), visitar la web de la API en <a href="https://scikit-learn.org/dev/api/sklearn.preprocessing.html">https://scikit-learn.org/dev/api/sklearn.preprocessing.html</a>


Veamos algún ejemplo:

In [2]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

# Datos originales
categoricos= np.array(['verde', 'rojo', 'ambar'])

# Transformación con LabelEncoder
print('\nEjemplo de LabelEncoder')
le= LabelEncoder()
le.fit(categoricos) # Ajustamos el codificador
ordinales= le.transform(categoricos)
print('Los datos categóricos \n{}\nhan sido transformados a ordinales con LabelEncoder: {}'.format(categoricos, ordinales))

# Transformación con OrdinalEncoder
print('\nEjemplo de OrdinalEncoder')
oe= OrdinalEncoder()
categoricos= categoricos.reshape(-1, 1) # Requiere datos en 2D
oe.fit(categoricos) # Ajustamos el codificador
ordinales= oe.transform(categoricos)
print('Los datos categóricos \n{}\nhan sido transformados a ordinales con OrdinalEncoder: {}'.format(categoricos, ordinales))

# Transformación con OneHotEncoder
print('\nEjemplo de OneHotEncoder')
ohe= OneHotEncoder(sparse_output= False) # True para una representación One-Hot dispersa
categoricos= categoricos.reshape(-1, 1) # Los datos deben proporcionarse como matriz
ohe.fit(categoricos)
one_hot= ohe.transform(categoricos)
print('Los datos categóricos \n{}\nhan sido transformados a One-Hot con OneHotEncoder: \n{}'.format(categoricos, one_hot))


# Ejemplo: Codificación binaria
print('\nEjemplo de OrdinalEncoder para binarización')
datos= np.array(['si', 'no', 'no', 'si', 'no']).reshape(-1, 1)
oe= OrdinalEncoder()
oe.fit(datos)
binario= oe.transform(datos)
print('Los datos de verdad \n{}\nhan sido transformados a binario con OrdinalEncoder: \n{}'.format(datos, binario))


Ejemplo de LabelEncoder
Los datos categóricos 
['verde' 'rojo' 'ambar']
han sido transformados a ordinales con LabelEncoder: [2 1 0]

Ejemplo de OrdinalEncoder
Los datos categóricos 
[['verde']
 ['rojo']
 ['ambar']]
han sido transformados a ordinales con OrdinalEncoder: [[2.]
 [1.]
 [0.]]

Ejemplo de OneHotEncoder
Los datos categóricos 
[['verde']
 ['rojo']
 ['ambar']]
han sido transformados a One-Hot con OneHotEncoder: 
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Ejemplo de OrdinalEncoder para binarización
Los datos de verdad 
[['si']
 ['no']
 ['no']
 ['si']
 ['no']]
han sido transformados a binario con OrdinalEncoder: 
[[1.]
 [0.]
 [0.]
 [1.]
 [0.]]


# **Transformaciones de datos**

Las transformaciones de datos más comunes suelen ser:

- **Cambios de escala** de un rango inicial [li, ui] a otro final [lf, uf]. Se efectúa con **sklearn.preprocessing.MinMaxScaler**.
- **Estandarización** de datos centrándolos en el 0 y modificando su varianza a 1. Se efectúa con **sklearn.preprocessing.StandardScaler**.

Veamos un ejemplo:

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Datos iniciales
precios= np.array([23.4, 100.8, 43.9, 55.6])

# Cambio de rango a [0,1] con MinMaxScaler
print('\nEjemplo de MinMaxScaler')
mme= MinMaxScaler(feature_range=(0,1))
print(precios)
precios= precios.reshape(-1, 1)
print(precios)
mme.fit(precios) # Requere datos 2D
precios_norm= mme.transform(precios)
print('Los precios originales \n{}\nse han normalizado al intervalo [0,1]:\n{}'.format(precios, precios_norm))

# Estandarización (normalización de datos con media 0 y std 1)
print('\nEjemplo de StandardScaler')
se= StandardScaler()
precios= precios.reshape(-1, 1)
se.fit(precios) # Requere datos 2D
precios_std= se.transform(precios)
print('Los precios originales \n{}\nse han estandarizado con media 0 y std 1:\n{}'.format(precios, precios_std))


Ejemplo de MinMaxScaler
[ 23.4 100.8  43.9  55.6]
[[ 23.4]
 [100.8]
 [ 43.9]
 [ 55.6]]
Los precios originales 
[[ 23.4]
 [100.8]
 [ 43.9]
 [ 55.6]]
se han normalizado al intervalo [0,1]:
[[0.        ]
 [1.        ]
 [0.26485788]
 [0.41602067]]

Ejemplo de StandardScaler
Los precios originales 
[[ 23.4]
 [100.8]
 [ 43.9]
 [ 55.6]]
se han estandarizado con media 0 y std 1:
[[-1.14700634]
 [ 1.58253373]
 [-0.42406614]
 [-0.01146125]]


## Transformaciones personalizadas

Se pueden incorporar transformaciones de datos personalizadas usando **FunctionTransformer**. Un ejemplo:

In [4]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Datos iniciales
precios= np.array([23.4, 100.8, 43.9, 55.6])

# Función para realizar una transformación logarítmica
log_transform= lambda x : np.log(x)

# Ejemplo de FunctionTransformer
print('\nEjemplo de FunctionTransformer')
ft= FunctionTransformer( log_transform )
precios_log= ft.transform(precios)
print('Los precios originales \n{}\nhan tenido transformación logarítmica a:\n{}'.format(precios, precios_log))



Ejemplo de FunctionTransformer
Los precios originales 
[ 23.4 100.8  43.9  55.6]
han tenido transformación logarítmica a:
[3.15273602 4.61313836 3.78191432 4.0181832 ]


# **Tratamiento de valores perdidos**

Un **valor perdido** es un valor desconocido dentro de una celda en nuestro conjunto de datos.

En **NumPy** se suelen representar mediante el valor **np.nan**.

Existen varias técnicas de tratamiento de valores perdidos:

- No considerar (eliminar) los atributos (columnas) que tengan valores perdidos (*poco recomendable si el atributo es importante o tiene información útil para el aprendizaje*)
- No considerar (eliminar) los patrones (filas) que tengan valores perdidos (*poco recomendable si el conjunto de datos es pequeño, o si hay muchas filas con valores perdidos que podrían marcar una diferencia en el aprendizaje).
- **Imputación de valores perdidos**: Tratar de aproximar los valores perdidos teniendo conocimiento del resto de valores en el mismo atributo.

Los algoritmos de imputación de valores perdidos se encuentran en el paquete **sklearn.impute**. Entre las técnicas de imputación de valores perdidos, las más simples son:

- **SimpleImputer(strategy='mean')**: Rellena los valores perdidos con la media del resto.
- **SimpleImputer(strategy='median')**: Rellena los valores perdidos con la mediana del resto.
- **SimpleImputer(strategy='most_frequent')**: Rellena los valores perdidos con la moda (valor más frecuente) del resto.
- **SimpleImputer(strategy='constant')**: Rellena los valores perdidos con un valor constante indicado por el programador.
- **KNNImputer(n_neighbors=n)**: Rellena los valores perdidos considerando los **n** patrones más similares al del valor perdido.

Más información en: <a href="https://scikit-learn.org/1.6/modules/impute.html">https://scikit-learn.org/1.6/modules/impute.html</a>

Veamos algunos ejemplos:

-

In [5]:
from sklearn.impute import SimpleImputer

# 10 valores obtenidos de una N(0,1)
datos= np.random.randn(10)

# Escogemos 2 valores que se van a perder
perdidos_idx= np.random.choice(range(len(datos)), size= 2, replace=False)
datos[perdidos_idx]= np.nan

print('Nuestro dataset es: \n{}'.format(datos))

# Ejemplo con SimpleImputer(strategy='mean')
print('\nSimpleImputer(strategy="mean"):')
si= SimpleImputer(strategy='mean')
datos= datos.reshape(-1, 1)
datos_finales= si.fit_transform(datos)
print('Resultado: {}'.format( datos_finales.squeeze() ))


# Ejemplo con SimpleImputer(strategy='median')
print('\nSimpleImputer(strategy="median"):')
si= SimpleImputer(strategy='median')
datos= datos.reshape(-1, 1)
datos_finales= si.fit_transform(datos)
print('Resultado: {}'.format( datos_finales.squeeze() ))


# Ejemplo con SimpleImputer(strategy='median')
print('\nSimpleImputer(strategy="constant", fill_value=0.0):')
si= SimpleImputer(strategy='constant', fill_value=0.0)
datos= datos.reshape(-1, 1)
datos_finales= si.fit_transform(datos)
print('Resultado: {}'.format( datos_finales.squeeze() ))

# Nuevos datos
datos= np.random.choice(range(2), size=20, p=[0.25, 0.75]).astype(float)
# Escogemos 2 valores que se van a perder
perdidos_idx= np.random.choice(range(len(datos)), size= 2, replace=False)
datos[perdidos_idx]= np.nan
print('\nNuevo dataset: {}'.format(datos))

# Ejemplo con SimpleImputer(strategy='most_frequent')
print('\nSimpleImputer(strategy="most_frequent"):')
si= SimpleImputer(strategy='most_frequent')
datos= datos.reshape(-1, 1)
datos_finales= si.fit_transform(datos)
print('Resultado: {}'.format( datos_finales.squeeze() ))


Nuestro dataset es: 
[ 1.6427128          nan -1.6656224          nan  0.19447611  0.43960081
  0.25218621  0.37880763 -0.62612858 -1.01910598]

SimpleImputer(strategy="mean"):
Resultado: [ 1.6427128  -0.05038418 -1.6656224  -0.05038418  0.19447611  0.43960081
  0.25218621  0.37880763 -0.62612858 -1.01910598]

SimpleImputer(strategy="median"):
Resultado: [ 1.6427128   0.22333116 -1.6656224   0.22333116  0.19447611  0.43960081
  0.25218621  0.37880763 -0.62612858 -1.01910598]

SimpleImputer(strategy="constant", fill_value=0.0):
Resultado: [ 1.6427128   0.         -1.6656224   0.          0.19447611  0.43960081
  0.25218621  0.37880763 -0.62612858 -1.01910598]

Nuevo dataset: [ 1.  1.  1.  0.  0.  1.  1.  0. nan  1.  1.  1.  1.  0. nan  1.  0.  1.
  1.  1.]

SimpleImputer(strategy="most_frequent"):
Resultado: [1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1.]


Veamos ahora un ejemplo algo más elaborado con KNNImputer

In [6]:
from sklearn.impute import KNNImputer

# Creación de nuevo dataset
nombres= ['Perico', 'Perica', 'Periquillo', 'Periquito', 'Pedro', 'Pedrito', 'Pedrín', 'Peter', 'Periquilla', 'Periquita']
edades= [40, 30, 10, 8, 70, 90, 45, 50, 77, 5]
categoria= ['Adulto', 'Adulto', np.nan, 'Niño', 'Mayor', np.nan, 'Adulto', np.nan, 'Mayor', 'Niño']

import pandas as pd
print('\nNuevo conjunto de datos')
df= pd.DataFrame({'nombre': nombres, 'edad': edades, 'categoria': categoria})
print(df)

# Nos quedamos con la edad y la categoría
datos= df[['edad', 'categoria']].to_numpy()
oe= OrdinalEncoder()
datos[:, 1]= oe.fit_transform(datos[:, 1].reshape(-1, 1)).squeeze()
print('Tras hacer el OrdinalEncoder, el dataset tiene tipo {} y es:\n{}'.format(datos.dtype, datos))
datos= datos.astype(float) # Transformamos los datos a reales

knne= KNNImputer(n_neighbors=2)
datos_final= knne.fit_transform(datos)
print('Los datos tras el KNNImputer con 2 vecinos son:\n{}'.format(datos_final))

# Transformación inversa del oe para mejorar la visualización
datos_reversed= datos_final.astype(object) # Transformamos los datos a objeto
datos_reversed[:, 1]= oe.inverse_transform(datos_reversed[:, 1].reshape(-1, 1)).squeeze()
print('Datos reconstruidos: \n{}'.format(datos_reversed))



Nuevo conjunto de datos
       nombre  edad categoria
0      Perico    40    Adulto
1      Perica    30    Adulto
2  Periquillo    10       NaN
3   Periquito     8      Niño
4       Pedro    70     Mayor
5     Pedrito    90       NaN
6      Pedrín    45    Adulto
7       Peter    50       NaN
8  Periquilla    77     Mayor
9   Periquita     5      Niño
Tras hacer el OrdinalEncoder, el dataset tiene tipo object y es:
[[40 0.0]
 [30 0.0]
 [10 nan]
 [8 2.0]
 [70 1.0]
 [90 nan]
 [45 0.0]
 [50 nan]
 [77 1.0]
 [5 2.0]]
Los datos tras el KNNImputer con 2 vecinos son:
[[40.  0.]
 [30.  0.]
 [10.  2.]
 [ 8.  2.]
 [70.  1.]
 [90.  1.]
 [45.  0.]
 [50.  0.]
 [77.  1.]
 [ 5.  2.]]
Datos reconstruidos: 
[[40.0 'Adulto']
 [30.0 'Adulto']
 [10.0 'Niño']
 [8.0 'Niño']
 [70.0 'Mayor']
 [90.0 'Mayor']
 [45.0 'Adulto']
 [50.0 'Adulto']
 [77.0 'Mayor']
 [5.0 'Niño']]


# **Selección y extracción de características**

La **selección de características** y la **extracción de características** se utiliza en aprendizaje automático con varios motivos, entre los que se destacan:

- Averiguar cuáles son los atributos que permiten predecir el resultado correcto con máxima precisión.
- Reducir la complejidad del modelo resultante.


En Scikit-learn disponemos de métodos de procesamiento de datos para extracción y selección de características.

## Extracción de características

La **extracción de características** trata de **combinar** dos o más atributos (columnas) existentes para dar lugar a un nuevo atributo que agregue la información de ambos de forma más compacta.

Veamos un ejemplo de extracción de características utilizando el análisis de componentes principales (PCA). Más información en <a hred="https://scikit-learn.org/1.5/modules/generated/sklearn.decomposition.PCA.html#sklearn.decomposition.PCA">https://scikit-learn.org/1.5/modules/generated/sklearn.decomposition.PCA.html#sklearn.decomposition.PCA</a>

In [7]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder

# Generación de conjunto de datos
x1= np.linspace(start=1, stop= 10, num=10)
x2= 2*x1 + np.random.normal(1, 3, 10)
y= ['Bajo' if x<=5 else 'Alto' for x in x1 ]

# Obtenemos nuestro conjunto de datos como si no supiésemos nada de él
print('Conjunto de datos:')
df= pd.DataFrame({'x1' : x1, 'x2' : x2, 'Tam' : y})
print(df)
print('\nOBJETIVO: Tratar de predecir la categoria "Tam" en función de (x1, x2)')

# Tratamos de reducir las características de los atributos

X= df[['x1', 'x2']].to_numpy()
y= df['Tam'].to_numpy()
y_enc= LabelEncoder().fit_transform(y)
print('\nHe transformado los datos iniciales y:\n{}\n con un LabelEncoder a:\n{}'.format(y, y_enc))

pca= PCA(n_components=2) # Iniciamos PCA con 2 componentes, dado que tenemos 2 atributos
pca.fit(X)

print('Componentes obtenidas (de mayor a menor importancia): \n{}'.format(pca.components_))
print('Varianza explicada: \n{}'.format(pca.explained_variance_))
print('Porcentaje de varianza explicada de cada componentes: \n{}'.format(pca.explained_variance_/np.sum(pca.explained_variance_)))

print('\nResulta que una única componente es capaz de explicar el 98.42\% del total de la varianza del conjunto de datos.')
print('Nos basta con una única componente que haga los cálculos.')

# Rehacemos PCA con 1 componente
pca= PCA(n_components=1) # Iniciamos PCA con 1 componente
pca.fit(X)
print('Componentes obtenidas (de mayor a menor importancia): \n{}'.format(pca.components_))
print('Varianza explicada: \n{}'.format(pca.explained_variance_))

print('Transformación de datos iniciales X=(x1, x2) de tamaño {} a X_pca:'.format(X.shape))
X_pca= pca.transform(X)
print('Datos transformados de tamaño {}:\n{}'.format(X_pca.shape, X_pca))

# Predicción de y a partir de X_pca usando SVC
from sklearn.svm import SVC
svc= SVC()
svc.fit(X_pca, y_enc)
y_pred= svc.predict(X_pca)

# Resultados
print('Los datos originales de salida eran: {}'.format(y_enc))
print('Los datos predichos de salida son: {}'.format(y_pred))
aciertos= 100*np.sum( y_enc==y_pred )/len(y_pred)
print('Tengo una tasa de aciertos del {}\%'.format(aciertos))



Conjunto de datos:
     x1         x2   Tam
0   1.0   1.081286  Bajo
1   2.0   0.938265  Bajo
2   3.0   5.301098  Bajo
3   4.0   6.235868  Bajo
4   5.0  12.504584  Bajo
5   6.0  11.805924  Alto
6   7.0  13.861191  Alto
7   8.0  16.790153  Alto
8   9.0  17.430262  Alto
9  10.0  26.672185  Alto

OBJETIVO: Tratar de predecir la categoria "Tam" en función de (x1, x2)

He transformado los datos iniciales y:
['Bajo' 'Bajo' 'Bajo' 'Bajo' 'Bajo' 'Alto' 'Alto' 'Alto' 'Alto' 'Alto']
 con un LabelEncoder a:
[1 1 1 1 1 0 0 0 0 0]
Componentes obtenidas (de mayor a menor importancia): 
[[ 0.3437409   0.93906453]
 [ 0.93906453 -0.3437409 ]]
Varianza explicada: 
[73.72815707  0.51608927]
Porcentaje de varianza explicada de cada componentes: 
[0.99304876 0.00695124]

Resulta que una única componente es capaz de explicar el 98.42\% del total de la varianza del conjunto de datos.
Nos basta con una única componente que haga los cálculos.
Componentes obtenidas (de mayor a menor importancia): 
[[0.3437409  

<>:31: SyntaxWarning: invalid escape sequence '\%'
<>:54: SyntaxWarning: invalid escape sequence '\%'
<>:31: SyntaxWarning: invalid escape sequence '\%'
<>:54: SyntaxWarning: invalid escape sequence '\%'
/tmp/ipykernel_334/4026937334.py:31: SyntaxWarning: invalid escape sequence '\%'
  print('\nResulta que una única componente es capaz de explicar el 98.42\% del total de la varianza del conjunto de datos.')
/tmp/ipykernel_334/4026937334.py:54: SyntaxWarning: invalid escape sequence '\%'
  print('Tengo una tasa de aciertos del {}\%'.format(aciertos))


**Aclaración final**: En el ejemplo anterior no siempre se devuelve el 100% de aciertos, como cabría esperar. ¿A qué es debido? Posiblemente a que no se ha realizado un correcto **preprocesamiento** (de hecho, no se ha hecho más que una transformación **LabelEncoder** en la salida.

Pruebe a realizar una estandarización de datos, o un cambio de escala a [-1, 1].

## Selección de características

La **selección de características** trata de **escoger** un subconjunto de atributos (columnas), entre todo el conjunto de datos, que permitan realizar una predicción de resultados exitosa. En SkLearn disponemos de varios métodos para seleccionar un subconjunto de atributos adecuado, dentro del paquete **sklearn.feature_selection**:

- Eliminación de atributos con baja varianza: **VarianceThreshold**
- Selección de los K mejores atributos (con respecto a una métrica de evaluación): **SelectKBest**
- Eliminación recursiva de atributos poco significativos: **RFE**

Algunos ejemplos de uso:

In [8]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Generación de conjunto de datos
x1= np.linspace(start=1, stop= 10, num=10)
x2= 2*x1 + np.random.normal(1, 3, 10)
y= ['Bajo' if x<=5 else 'Alto' for x in x1 ]

# Obtenemos nuestro conjunto de datos como si no supiésemos nada de él
print('Conjunto de datos:')
df= pd.DataFrame({'x1' : x1, 'x2' : x2, 'Tam' : y})
print(df)
print('\nOBJETIVO: Tratar de predecir la categoria "Tam" en función de (x1, x2)')
X= df[['x1', 'x2']].to_numpy()
y= df['Tam'].to_numpy()

print('Datos de entrada X:\n{}'.format(X))
print('Varianza de cada columna: {}'.format(np.var(X, axis=0)))


# Codificación de salidas
y_enc= LabelEncoder().fit_transform(y)
print('\nHe transformado los datos iniciales y:\n{}\n con un LabelEncoder a:\n{}'.format(y, y_enc))


# Ejemplo de uso de VarianceThreshold
from sklearn.feature_selection import VarianceThreshold

vc= VarianceThreshold(threshold= 10)
X_final= vc.fit_transform(X)
print('\nEjemplo de uso de VarianceThreshold con threshold= 10')
print('La selección de características me da el conjunto X_final:\n{}'.format(X_final))



# PREPROCESAMIENTO: Tratamos de reducir las diferencias estadísticas de rango de los atributos
mme= MinMaxScaler()
X= mme.fit_transform(X)
print('Datos de entrada X escalados a [0,1]')
print(X)
print('Varianza de cada columna: {}'.format(np.var(X, axis=0)))



# Ejemplo de uso de SelectKBest
from sklearn.feature_selection import SelectKBest, chi2

skb= SelectKBest(score_func= chi2, k=1) # Nos quedamos con 1 atributo
skb.fit(X, y)
X_final= skb.transform(X)
print('\nEjemplo de uso de SelectKBest con score_func= chi2, k=1')
print('La selección de características me da el conjunto X_final:\n{}'.format(X_final))



# Ejemplo de uso de eliminación iterativa de atributos (RFE)
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier

rfe= RFE(estimator= DecisionTreeClassifier(), n_features_to_select=1)
rfe.fit(X, y)
X_final= rfe.transform(X)
print('\nEjemplo de uso de RFE con estimador eficiente DT, n_features_to_select=1')
print('La selección de características me da el conjunto X_final:\n{}'.format(X_final))



# Me quedo con este último como ejemplo para entrenar el clasificador

# Predicción de y a partir de X_pca usando SVC
from sklearn.svm import SVC
svc= SVC()
svc.fit(X_final, y_enc)
y_pred= svc.predict(X_final)

# Resultados
print('Los datos originales de salida eran: {}'.format(y_enc))
print('Los datos predichos de salida son: {}'.format(y_pred))
aciertos= 100*np.sum( y_enc==y_pred )/len(y_pred)
print('Tengo una tasa de aciertos del {}\%'.format(aciertos))





<>:82: SyntaxWarning: invalid escape sequence '\%'
<>:82: SyntaxWarning: invalid escape sequence '\%'


Conjunto de datos:
     x1         x2   Tam
0   1.0   7.888955  Bajo
1   2.0   2.439267  Bajo
2   3.0   9.065762  Bajo
3   4.0   9.089545  Bajo
4   5.0   9.405495  Bajo
5   6.0  14.898879  Alto
6   7.0  14.095882  Alto
7   8.0  13.004805  Alto
8   9.0  23.795030  Alto
9  10.0  23.059007  Alto

OBJETIVO: Tratar de predecir la categoria "Tam" en función de (x1, x2)
Datos de entrada X:
[[ 1.          7.88895505]
 [ 2.          2.43926669]
 [ 3.          9.06576161]
 [ 4.          9.08954514]
 [ 5.          9.40549491]
 [ 6.         14.89887894]
 [ 7.         14.09588152]
 [ 8.         13.00480525]
 [ 9.         23.79503003]
 [10.         23.05900662]]
Varianza de cada columna: [ 8.25       40.28041837]

He transformado los datos iniciales y:
['Bajo' 'Bajo' 'Bajo' 'Bajo' 'Bajo' 'Alto' 'Alto' 'Alto' 'Alto' 'Alto']
 con un LabelEncoder a:
[1 1 1 1 1 0 0 0 0 0]


/tmp/ipykernel_334/702108809.py:82: SyntaxWarning: invalid escape sequence '\%'
  print('Tengo una tasa de aciertos del {}\%'.format(aciertos))



Ejemplo de uso de VarianceThreshold con threshold= 10
La selección de características me da el conjunto X_final:
[[ 7.88895505]
 [ 2.43926669]
 [ 9.06576161]
 [ 9.08954514]
 [ 9.40549491]
 [14.89887894]
 [14.09588152]
 [13.00480525]
 [23.79503003]
 [23.05900662]]
Datos de entrada X escalados a [0,1]
[[0.         0.25518584]
 [0.11111111 0.        ]
 [0.22222222 0.31029071]
 [0.33333333 0.31140439]
 [0.44444444 0.32619898]
 [0.55555556 0.5834309 ]
 [0.66666667 0.54582993]
 [0.77777778 0.49473945]
 [0.88888889 1.        ]
 [1.         0.96553514]]
Varianza de cada columna: [0.10185185 0.08832096]

Ejemplo de uso de SelectKBest con score_func= chi2, k=1
La selección de características me da el conjunto X_final:
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]

Ejemplo de uso de RFE con estimador eficiente DT, n_features_to_select=1
La selección de características me da el conjunto X_final:
[[0.   

# **Ejercicio**

Lea el conjunto de datos de la Flor de Iris (sea desde SkLearn directamente o desde Pandas en la URL <a href="https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv">https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv</a>
). El ejercicio consiste en:

**Desarrollar un clasificador que permita distinguir la flor *Setosa* del resto de tipos de flores**.

<b><u>Algunas claves metodológicas</u></b>:

- Tras leer el conjunto de datos, compruebe qué atributos predictores (entradas) hay y cuál es el atributo objetivo o *clase* (salida).
- Compruebe si hay valores perdidos. Si los hay, escoja un método adecuado para tratarlos.
- Transforme los tipos de flor considerando que sólo es necesario saber si el tipo es **Setosa** o **no es Setosa**.
- Realice un **análisis exploratorio de datos**: Visualice cómo se distribuyen las clases con respecto a pares de atributos (gráficas scatterplots), cuál es el rango de valores de cada uno (histogramas, boxplots), etc.
- Realice transformaciones a los datos si es necesario (cambios de escala, estandarización...)
- Realice una selección de características o una extracción de características si es necesario.
- Use el clasificador SVC como medio de clasificar el tipo de flor correcto.
- Calcule la tasa de aciertos de su modelo (**spoiler: debería salir un 100% de aciertos en cualquier caso**)


**Trate de encontrar un clasificador SVC que permita obtener la máxima tasa de aciertos posible al detectar la flor Setosa usando el mínimo número de entradas (columnas) posible.**

In [9]:
# Solución